### ISSUE TITLE
Suitability for CI?

### ISSUE THREAD

**Issue by michaeljones** [wolfadex/elm-license-finder#7]
I was very interested to see this tool and very grateful for the work you've put in. I've recently had a brush with some GPL code on a project which caught me off guard so I'm a bit sensitive to this stuff at the moment and so keen to use your project.

I think in my ideal situation I would set your tool up on CI with a list of acceptable licenses and CI would fail if a package is added with an unrecognised license. The licenses could be provided in a config file or via command line:
```
elm-license-finder --allow "BSD-3-Clause" --allow "MIT" --allow "MPL-2.0" 
```
or something like that?

Do you think that would be possible or reasonable for the project? Perhaps there is another way?

**Comment by michaeljones** [comment]
I've realised that as you've exposed it as a module too then I can work with that instead. Thanks!

**Comment by wolfadex** [comment]
I really like this idea. What do you think of something like
```
elm-license-finder --white-list "BSD-3-Clause" "MPL-2.0" --black-list "MIT"
```
where you pass in an array of values (you could also do `--white-list "BSD-3-Clause" --white-list "MPL-2.0"`). `--white-list` would take precedence over `--black-list`.

Examples:
Given `elm-license-finder --black-list "MIT"`, the cli would fail if any dependency has a license of `MIT`

Given `elm-license-finder --white-list "MPL-2.0"`, the cli would fail if any dependency isn't `MPL-2.0`

Given `elm-license-finder --white-list "MPL-2.0" --black-list "MIT"`, the cli would fail if any dependecy isn't `MPL-2.0`

---

This would also mean a change to the default output I think. I'm thinking to change it do default to returning the results as JSON (if successful) and adding `--table` to display it in the table format.

What do you think?

**Comment by michaeljones** [comment]
Thanks for the quick response. I can now share a bit more experience. I've been setting up a CI check for licenses at work today. The 20-30 Elm dependencies have just 3 licenses between them which would suit the kind of command we've indicated here.

Additionally, the npm packages we use have something closer to 30-40 licenses between them including some which come as combinations like `(MIT OR Apache-2.0)`. In this situation I'm more comfortable with a config file than with command line arguments. 

I ended up using [license-checker](https://www.npmjs.com/package/license-checker) for npm packages which has a similar `black-list` and `white-list` approach though they call them `failOn` and `onlyAllow`. 

In the end, the approach I took was to write a javascript script that imports both license-check and your project and runs custom checks on that output which allows me to have a long list of acceptable licenses written directly into the javascript (typescipt) code along with a list of package exceptions that need to be handled separately.

I seems that the license-checker could not always find the license or the some packages have it poorly specified so it seems like I will need to manually review a bunch of packages and add explicit exceptions (name & version) to my script to consider them valid. Something like that might be hard to additionally accommodate on the command line. 

Something else that came up on the npm side was to run the checks for the multiple different package.json files that we have in our mono-repo. I'm not sure if elm-license-finder currently deals with the idea of multiple different `elm.json` files in a project but that could be something to consider one day. Or you could leave it to the user to for-loop over the different files which is what I've done.

I hope some of this is useful. I imagine you have some experience yourself! I just wanted to share a bit.

**Comment by wolfadex** [comment]
I'm kinda thinking that it might be best to require the user to specify the output style and provide more options. Something like `--output=table`, `--output=json`, `--output=csv`, etc. This would keep the tool relatively simple (collect license information) and leave the handling of the output up to the user.

My thinking is that this tool should follow the Unix philosophy of "... do one thing well." If users want to filter their JSON on the command line then they should use the tool that's best for that and I shouldn't make assumptions about what they need/want.

**Comment by michaeljones** [comment]
Yeah, I think I agree. My minimal experience has already left me happy that I've reached for the exposed API (and happy that you exposed it!) 

I realise I didn't answer your question before. I think that the table is a reasonable default output but options for csv or json are good to have.

I've just checked `license-checker` exports a tree format but it is only one level deep:

```
...
├─ yn@3.1.1
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/sindresorhus/yn
│  ├─ publisher: Sindre Sorhus
│  ├─ email: sindresorhus@gmail.com
│  ├─ url: sindresorhus.com
│  ├─ path: /home/michael/root/projects/hive/server/node_modules/yn
│  └─ licenseFile: /home/michael/root/projects/hive/server/node_modules/yn/license
└─ zip-stream@2.1.2
   ├─ licenses: MIT
   ├─ repository: https://github.com/archiverjs/node-zip-stream
   ├─ publisher: Chris Talkington
   ├─ url: http://christalkington.com/
   ├─ path: /home/michael/root/projects/hive/server/node_modules/zip-stream
   └─ licenseFile: /home/michael/root/projects/hive/server/node_modules/zip-stream/LICENSE
```
In this case, I suspect that a json object output would be almost as readable and more useful. Perhaps there are situations where the output has nested levels though and I can imagine the "tree" display being more friendly in that case.

**Comment by wolfadex** [comment]
In PR #9 I've added support for both json and csv output from the cli, as well as being able to specify a directory from the cli. This is all in version 1.2.0 which is now published too.

**Comment by wolfadex** [comment]
> output has nested levels

Elm actually doesn't have nested levels per se. All the dependencies of an `application` are listed either in `direct` or `indirect` which is super convenient. If you have a `package` then my tool only lists the "direct" dependencies currently as that's all there is.

I haven't seen many, if any, elm packages with multiple nested dependencies yet. Most tend to rely on the core packages and maybe 1-3 other packages, who in turn only rely on core ones.
